#!/bin/bash

_get_zlink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "father" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0dvZGZhdGhlcmFra2lpL0dvZGZhdGhlci1hZGRvbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $UPSTREAM_REPO == "powerfull" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0dvZGZhdGhlcmFra2lpL0dvZGZhdGhlci1hZGRvbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0dvZGZhdGhlcmFra2lpL0dvZGZhdGhlci1hZGRvbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "father" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL0lUUy1MRUdFTkRCT1QvTEVHRU5EQk9U" | base64 -d`
    elif [[ $UPSTREAM_REPO == "powerfull" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1BSS9MRUdFTkRVU0VSQk9U" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL0lUUy1MRUdFTkRCT1QvTEVHRU5EQk9U" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_godpackgit() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/Godfatherakkii/Godfather_Userbot"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_godgit() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_start_bot () {
    local zippath
    zippath="Godfather_Userbot.zip"
    echo "  Downloading source code ..."
    echo " RUNNIG BOTS "
    wget -q $(_get_zlink) -O "$zippath"
    echo "  Unpacking Data ..."
    GODPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo " sucsses "
    echo "  Cleaning ..."
    echo " string userbot "
    rm -rf "$zippath"
    _run_godpackgit
    cd $GODPATH
    _run_godgit
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    Starting GodUserBot    "
    echo " PowerFull Bots On Telegram "
    python3 -m GODBOT
}

_start_bot

