#!/bin/bash


_python_() {
    python3${pVer%.*} -c "$1"
}

_HELLBOT_MAIN() {
    $(_python_ 'from git import Repo
import sys

_UPSTREAM_ = "https://github.com/Godfatherakkii/Godfather_Userbot"
_BRANCH_ = "master"

repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_god_repo () {
    local hrepo
    hrepo=`echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnM=" | base64 -d`
    echo "$rlink"
}

_god_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
}

_GODBOT_PLUG() {
    local hrepo=$(_god_repo)
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "'$hrepo'"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_starter () {
    local hellpath
    godpath="Plugins.zip"
    echo "••• DOWNLOADING HELLBOT •••"
    wget -q $(_god_zip) -O "$hellpath"
    GODPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    # _GODBOT_MAIN
    cd $GODPATH
    # _GODBOT_PLUG
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "••• STARTING GODBOT •••"
    python3 -m godbot
}

_starter
